In [20]:
import yfinance as yf
import pandas as pd

# Download Apple 1-hour data
df = yf.download(
    tickers="AAPL",
    interval="1h",
    period="60d",      # last 60 days (safe for Yahoo hourly)
    auto_adjust=False,
    progress=False
)

df.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL
Datetime,,,,,,
2025-11-19 14:30:00+00:00,271.850006,271.850006,272.209991,265.500000,265.524994,6778562
2025-11-19 15:30:00+00:00,269.730011,269.730011,272.010010,269.320099,271.850098,2792346
2025-11-19 16:30:00+00:00,270.399994,270.399994,270.654999,269.529999,269.750000,2001030
2025-11-19 17:30:00+00:00,270.029999,270.029999,271.309998,269.619995,270.459991,2049762
2025-11-19 18:30:00+00:00,269.670013,269.670013,271.010010,269.630005,270.010010,1644126

In [25]:
df.to_csv("../data/raw/AAPL_1h.csv")

In [22]:
import pandas as pd

# Read CSV with the correct header row (Datetime row)
df = pd.read_csv("../data/raw/AAPL_1h.csv", header=[0,1], index_col=0)

# Convert index to datetime
df.index = pd.to_datetime(df.index)

df.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL
Datetime,,,,,,
2025-11-19 14:30:00+00:00,271.850006,271.850006,272.209991,265.500000,265.524994,6778562
2025-11-19 15:30:00+00:00,269.730011,269.730011,272.010010,269.320099,271.850098,2792346
2025-11-19 16:30:00+00:00,270.399994,270.399994,270.654999,269.529999,269.750000,2001030
2025-11-19 17:30:00+00:00,270.029999,270.029999,271.309998,269.619995,270.459991,2049762
2025-11-19 18:30:00+00:00,269.670013,269.670013,271.010010,269.630005,270.010010,1644126

In [23]:
# Keep only the first level (Adj Close, Close, High, Low, Open, Volume)
df.columns = df.columns.get_level_values(0)

df.head()

Price,Adj Close,Close,High,Low,Open,Volume
Datetime,,,,,,
2025-11-19 14:30:00+00:00,271.850006,271.850006,272.209991,265.500000,265.524994,6778562
2025-11-19 15:30:00+00:00,269.730011,269.730011,272.010010,269.320099,271.850098,2792346
2025-11-19 16:30:00+00:00,270.399994,270.399994,270.654999,269.529999,269.750000,2001030
2025-11-19 17:30:00+00:00,270.029999,270.029999,271.309998,269.619995,270.459991,2049762
2025-11-19 18:30:00+00:00,269.670013,269.670013,271.010010,269.630005,270.010010,1644126

In [24]:
print(df.columns)
print(df.index.min(), "->", df.index.max())
print(df.isna().sum())

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str', name='Price')
2025-11-19 14:30:00+00:00 -> 2026-02-17 20:30:00+00:00
Price
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64