In [1]:
import yfinance as yf
import pandas as pd

# Download Apple 1-hour data
df = yf.download(
    tickers="AAPL",
    interval="1h",
    period="60d",
    auto_adjust=False,
    progress=False
)

# Flatten the MultiIndex columns immediately
df.columns = df.columns.get_level_values(0)

# Reset index so Datetime becomes a normal column
df = df.reset_index()

In [2]:
df.to_csv("../data/raw/AAPL_1h.csv", index=False)

In [3]:
import pandas as pd

# Read CSV with the correct header row (Datetime row)
df = pd.read_csv("../data/raw/AAPL_1h.csv", header=[0,1], index_col=0)

# Convert index to datetime
df.index = pd.to_datetime(df.index)

df.head()

Datetime,Adj Close,Close,High,Low,Open,Volume
2025-12-05 14:30:00+00:00,280.4551086425781,280.4551086425781,281.1400146484375,279.2699890136719,280.5400085449219,4393145
2025-12-05 15:30:00+00:00,279.295013,279.295013,280.980011,279.290009,280.459991,3579247
2025-12-05 16:30:00+00:00,278.315002,278.315002,279.329987,278.114990,279.299988,2319755
2025-12-05 17:30:00+00:00,279.440002,279.440002,279.480103,278.049988,278.315002,1693305
2025-12-05 18:30:00+00:00,279.233795,279.233795,279.570007,278.584991,279.480011,1553832
2025-12-05 19:30:00+00:00,278.801392,278.801392,279.299988,278.540009,279.230011,1937238

In [4]:
# Keep only the first level (Adj Close, Close, High, Low, Open, Volume)
df.columns = df.columns.get_level_values(0)

df.head()

Datetime,Adj Close,Close,High,Low,Open,Volume
2025-12-05 15:30:00+00:00,279.295013,279.295013,280.980011,279.290009,280.459991,3579247
2025-12-05 16:30:00+00:00,278.315002,278.315002,279.329987,278.114990,279.299988,2319755
2025-12-05 17:30:00+00:00,279.440002,279.440002,279.480103,278.049988,278.315002,1693305
2025-12-05 18:30:00+00:00,279.233795,279.233795,279.570007,278.584991,279.480011,1553832
2025-12-05 19:30:00+00:00,278.801392,278.801392,279.299988,278.540009,279.230011,1937238

In [5]:
print(df.columns)
print(df.index.min(), "->", df.index.max())
print(df.isna().sum())

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str', name='Datetime')
2025-12-05 15:30:00+00:00 -> 2026-03-04 20:30:00+00:00
Datetime
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64